sudo: false
language: node_js
node_js:
  - "10"
branches:
  only:
    - master
cache: yarn
install:
  - yarn install
script:
  - yarn test
  - yarn build
deploy:
  script:
    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
    - npm run release
