sudo: false
language: node_js
node_js:
  - "10"
branches:
  only:
    - master
cache:
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn test
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_API_TOKEN"
  skip_cleanup: true
  on:
    all_branches: true
