sudo: false
language: node_js
node_js:
  - "10"
branches:
  only:
    - master
cache: yarn
install:
  - yarn install
script:
  - yarn test
  - yarn build
deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/deploy.sh
