sudo: false
language: node_js
node_js:
- '10'
branches:
  only:
  - master
cache: yarn
install:
- yarn install
script:
- yarn test
- yarn build
deploy:
  provider: npm
  email: sowdri@gmail.com
  api_token: Ahx+zF7fKE1QiQA8cG6By2V0sjIq+saecsXoJz7j6sOR4dCRhGwZ65WWPMeqXDQxLCrEA/tyzIm+IV56T9wZx0yNB3dwjAGiSmfv+SuFu3Mhw2fQqa+oZGa6XcjAX5rtekSs2dGoVbfj4443W1DMxjPohBciHiPs5cpOn+0AJOtyv3BwDR3JyhoGFzaNsFDiwMkcC3BGyCC1qPdEsGUxf35a0VmbLEcS+zRKydm2iv3gRVTH3g3lkmDKvnaSNbKVhkGrbw/ra+iN3vb1sIR539AoSjOzDa064bWNnPTpQ0B1hcs59w3bR/fapBbsQqjP+wSsNMpY9bXUYLcMdI5/b9KK7Wp4iEBiwEfe9jhgkIU9aAKzSYvkfRUbLoeHwowUMo+zfmxdtMBSveUHrktN/h8Nt/5AKxoZoVYebIMAdFmliAPCLw5SeY5FONlloe1corGFA/T7D7DkIpCvCOxmsMZh5kq+ZbjTrjo6dZebtpUv0cI92SGG6G7yuuCBXgql/28g0cUn0QjcFD6TfIJK/1i8m5rcCZGvg6jRT+kb+//j85xBY1ZPCo9zeOvRk8MoDIG91lItbye5lQZsYz6OKEa8mOrn2uJjzEvwWnwuQWzhKO0iiYdbRVswat2JELR5Kp5JHiqGcuYTV2czlnsUAifJ5NOltWlk7IZeoVY8ekE=
  edge: true
  on:
    repo: sowdri/nutso
  api_key:
    secure: HqkIYl8dOtA4UOHqDqmNHeblSCFa5pr7ztpjcVSgT96huEqms2YDYXR1Yi451W0mPd05uAlAp3ausCyA5GvkVf8qDM+DsD9MFQ33ohRUGv1KgnwkvjK/CBuqnU7HkaAcHWrUZ4dUN0MpKlabVY839CujmR4bI0PJKn/vSp0Mt3OYKostIHEVygyj4upu6kbkgls8cBFNOdb4ZL6T7KqWglYa+RXozv93zoQeRYRdLUNzDHtrILdWsmnvgrJMeG07Pxjvv7OMK9nedTNp3KrtRA8jTM/ffBcjINmDafADbaFayWZl6H0xzfcwHHfHlljedJ4WRcPYIMbhSmZWNlzMfv9yFDrTYebuVqDrpKjpYeHfzrKg8ZQv0BEJzEKFTT76wa32zqHPvrC1b2cxJC+B1b0XhBoRkQ4FFYZ2bOJbX0mdTEraG3Utns/UhT5eGucINs3MjOBddVJ+/f5j2aMHYMu1olmDpE49+rldYLNbH4uFxnNYxmK/u8hXKaM2CdAfg6CNC6laMQuX61hCQHLdhLViR+d5UcUv5brXViljphdXDUS8d/d6npQPDDlk0P04RdesBjIchfTOpvOs5Z7EFiN1Vkw9XjVMvD/iqqmk4GPuXaMsMC7eTFFL10spgdG2DBpmfAn2ZvnULSOJzSCEmU51N9XFLgP/1giHfLIZN7Q=
